# Copyright (C) 2024 BIRU
#
# This file is part of Tenzu.
#
# Tenzu is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# You can contact BIRU at ask@biru.sh

# Generated by Django 5.1.3 on 2025-01-15 14:57

from django.db import migrations, models
from django.db.models import OuterRef, Subquery, Value
from django.db.models.functions import Concat


def fill_landing_pages(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Workflow = apps.get_model("workflows", "Workflow")
    subquery = Workflow.objects.filter(project=OuterRef("pk"))
    Project.objects.update(
        landing_page=Concat(
            Value("kanban/"),
            Subquery(subquery.values("slug")[:1], output_field=models.CharField()),
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_projecttemplate_to_generic_jsonfield"),
        (
            "workflows",
            "0004_remove_workflow_workflows_workflow_unique_project_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="landing_page",
            field=models.CharField(default="", blank=True, max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(fill_landing_pages, migrations.RunPython.noop),
    ]
