# Copyright (C) 2024 BIRU
#
# This file is part of Tenzu.
#
# Tenzu is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# You can contact BIRU at ask@biru.sh

# Generated by Django 5.1.3 on 2025-04-05 23:31

from django.db import migrations

from projects.projects.migrations._data import create_initial_project_template


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_remove_project_public_permissions"),
    ]

    operations = [
        migrations.RunPython(
            create_initial_project_template, migrations.RunPython.noop
        ),
    ]
