# Copyright (C) 2025 BIRU
#
# This file is part of Tenzu.
#
# Tenzu is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# You can contact BIRU at ask@biru.sh

# Generated by Django 5.2.3 on 2025-08-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_authdata_extra_to_generic_jsonfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="accepted_terms",
        ),
        migrations.AddField(
            model_name="user",
            name="accepted_privacy_policy",
            field=models.DateTimeField(
                null=True, verbose_name="acceptance date privacy policy"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="accepted_terms_of_service",
            field=models.DateTimeField(
                null=True, verbose_name="acceptance date terms of service"
            ),
        ),
    ]
