# Copyright (C) 2026 BIRU
#
# This file is part of Tenzu.
#
# Tenzu is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# You can contact BIRU at ask@biru.sh

# Generated by Django 6.0.6 on 2026-08-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0006_migrate_description_to_description_binary"),
        ("stories_tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="tags",
            field=models.ManyToManyField(
                related_name="stories",
                through="stories_tags.StoryTagAssignment",
                through_fields=("story", "tag"),
                to="stories_tags.storytag",
                verbose_name="tags",
            ),
        ),
    ]
