# Copyright (C) 2026 BIRU
#
# This file is part of Tenzu.
#
# Tenzu is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# You can contact BIRU at ask@biru.sh

# Generated by Django 6.0.6 on 2026-08-17 20:01

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

import ninja_jwt.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0010_remove_project_public_permissions"),
        ("stories", "0006_migrate_description_to_description_binary"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, verbose_name="label")),
                (
                    "color",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="color",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_tags",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "story tag",
                "verbose_name_plural": "story tags",
                "ordering": ["project", django.db.models.functions.text.Lower("label")],
            },
        ),
        migrations.CreateModel(
            name="StoryTagAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=ninja_jwt.utils.aware_utcnow, verbose_name="created at"
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_tag_assignments",
                        to="stories.story",
                        verbose_name="story",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_tag_assignments",
                        to="stories_tags.storytag",
                        verbose_name="tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "story tag assignment",
                "verbose_name_plural": "story tag assignments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="storytag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("label"),
                models.F("project"),
                name="stories_tags_storytag_unique_project_lower_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="storytag",
            constraint=models.CheckConstraint(
                condition=models.Q(("color__gte", 1), ("color__lte", 20)),
                name="stories_tags_storytag_color_between_1_and_num_colors",
            ),
        ),
        migrations.AddIndex(
            model_name="storytagassignment",
            index=models.Index(
                fields=["story", "tag"], name="stories_tag_story_i_c24fa2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storytagassignment",
            constraint=models.UniqueConstraint(
                fields=("story", "tag"),
                name="stories_tags_storytagassignment_unique_story_tag",
            ),
        ),
    ]
