# Copyright (C) 2026 BIRU
#
# This file is part of Tenzu.
#
# Tenzu is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# You can contact BIRU at ask@biru.sh

# Generated by Django 6.0.6 on 2026-06-25 13:13

import uuid

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models

import feeds.models
import ninja_jwt.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=ninja_jwt.utils.aware_utcnow, verbose_name="created at"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="modified at"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                (
                    "content",
                    models.TextField(
                        help_text="Markdown content.", verbose_name="content"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("release", "Release"),
                            ("call_to_action", "Call to action"),
                        ],
                        max_length=32,
                        verbose_name="type",
                    ),
                ),
                (
                    "action_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="action title",
                    ),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, default="", verbose_name="action url"),
                ),
                (
                    "active_period",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default=feeds.models.default_active_period,
                        verbose_name="active period",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "feed item",
                "verbose_name_plural": "feed items",
                "ordering": ["-active_period"],
            },
        ),
        migrations.CreateModel(
            name="FeedItemReadStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        default=ninja_jwt.utils.aware_utcnow, verbose_name="read at"
                    ),
                ),
                (
                    "feed_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_statuses",
                        to="feeds.feeditem",
                        verbose_name="feed item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_item_read_statuses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "feed item read status",
                "verbose_name_plural": "feed item read statuses",
            },
        ),
        migrations.AddField(
            model_name="feeditem",
            name="read_by",
            field=models.ManyToManyField(
                related_name="read_feed_items",
                through="feeds.FeedItemReadStatus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="read by",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeditemreadstatus",
            constraint=models.UniqueConstraint(
                fields=("feed_item", "user"),
                name="feeds_feeditemreadstatus_unique_user_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeditem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("active_period__upper_inf", True), ("type", "release")
                ),
                fields=("type",),
                name="feeds_feeditem_unique_active_release",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeditem",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("type", "maintenance"))
                | models.Q(("type", "release")),
                expressions=[("active_period", "&&"), ("type", "=")],
                name="feeds_feeditem_no_overlapping_maintenance_or_release",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeditem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "call_to_action"), _negated=True),
                    models.Q(
                        models.Q(("action_title", ""), _negated=True),
                        models.Q(("action_url", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="feeds_feeditem_cta_requires_action_fields",
            ),
        ),
    ]
