# Copyright (C) 2026 BIRU
#
# This file is part of Tenzu.
#
# Tenzu is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# You can contact BIRU at ask@biru.sh

# Generated by Django 6.0.6 on 2026-06-23 14:59

import django.core.serializers.json
from asgiref.sync import async_to_sync
from django.db import migrations, models

from import_export.migrations._data import (
    fill_pending_invites_for_importations_in_batches,
)
from import_export.models import ImportationStatus


def from_success_to_action(apps, schema_editor):
    ProjectImportation = apps.get_model("import_export", "ProjectImportation")
    async_to_sync(fill_pending_invites_for_importations_in_batches)(ProjectImportation)


def from_action_to_success(apps, schema_editor):
    ProjectImportation = apps.get_model("import_export", "ProjectImportation")
    ProjectImportation.objects.filter(status=ImportationStatus.ACTION_NEEDED).update(
        status=ImportationStatus.SUCCESS
    )


class Migration(migrations.Migration):
    dependencies = [
        ("import_export", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimportation",
            name="pending_invites",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.RunPython(
            from_success_to_action, reverse_code=from_action_to_success
        ),
    ]
