# Copyright (C) 2024 BIRU
#
# This file is part of Tenzu.
#
# Tenzu is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# You can contact BIRU at ask@biru.sh

# Generated by Django 5.1.3 on 2025-04-03 14:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import base.db.models
import base.db.models.fields
import base.utils.datetime


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=base.db.models.uuid_generator,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=base.utils.datetime.aware_utcnow,
                        verbose_name="created at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workspaces.workspace",
                        verbose_name="workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace membership",
                "verbose_name_plural": "workspace memberships",
                "ordering": ["workspace", "user"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=base.db.models.uuid_generator,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "slug",
                    base.db.models.fields.LowerSlugField(
                        blank=True, max_length=250, verbose_name="slug"
                    ),
                ),
                (
                    "order",
                    models.BigIntegerField(
                        default=base.utils.datetime.timestamp_mics, verbose_name="order"
                    ),
                ),
                (
                    "is_owner",
                    models.BooleanField(default=False, verbose_name="is_owner"),
                ),
                (
                    "editable",
                    models.BooleanField(default=True, verbose_name="editable"),
                ),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("modify_workspace", "Modify info of workspace"),
                                ("delete_workspace", "Delete the workspace"),
                                ("create_project", "Create project in workspace"),
                                ("create_modify_member", "Create or modify a member"),
                                ("delete_member", "Delete a member"),
                            ],
                            max_length=40,
                        ),
                        default=list,
                        size=None,
                        verbose_name="permissions",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="workspace_roles",
                        through="workspaces_memberships.WorkspaceMembership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="users",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="workspaces.workspace",
                        verbose_name="workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace role",
                "verbose_name_plural": "workspace roles",
                "ordering": ["workspace", "order", "name"],
            },
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="memberships",
                to="workspaces_memberships.workspacerole",
                verbose_name="role",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacerole",
            index=models.Index(
                fields=["workspace", "slug"], name="workspaces__workspa_919d77_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacerole",
            constraint=models.UniqueConstraint(
                fields=("workspace", "slug"),
                name="workspaces_memberships_workspacerole_unique_workspace_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacerole",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"),
                name="workspaces_memberships_workspacerole_unique_workspace_name",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(
                fields=["workspace", "user"], name="workspaces__workspa_e36c45_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacemembership",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user"),
                name="workspaces_memberships_workspacemembership_unique_workspace_user",
            ),
        ),
    ]
